<a href="https://colab.research.google.com/github/skgolammahmud/deep_learning/blob/main/tensorflow_essentials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.17.1


In [2]:
# creating a scalar
scalar = tf.constant(1)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=1>

#### A scalar is known as a rank 0 tensor. Because it has no dimensions (it's just a number)

In [3]:
# number of dimensions
scalar.ndim

0

In [4]:
# creating a vector (more than 0 dimensions)
vector = tf.constant([1,2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [5]:
# number of dimentions
vector.ndim

1

In [6]:
# creating a matrix (more than 1 dimentions)
matrix = tf.constant([[1,2],
                      [3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [7]:
# number of dimentions
matrix.ndim

2

#### By default, `tf` creates tensors with either an `int32` or `float32` dtype.

In [8]:
# now, creating another matrix and defining the dtype
custom_matrix = tf.constant([[1,2],
                             [3,4]], dtype=tf.float16)
custom_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float16)>

In [9]:
# dtype is different, but dimension will be same
custom_matrix.ndim

2

In [10]:
# more than 2 dimensions
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[1,2,3],
                       [4,5,6]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [11]:
# number of dimensions
tensor.ndim

3

##### This is known as a rank 3 tensor (3 dimensional)

In [12]:
changable_tensor = tf.Variable([1,2])
unchangeable_tensor = tf.constant([1,2])

In [13]:
# in order to change element, need to use `.assign()` method
changable_tensor[0].assign(100)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([100,   2], dtype=int32)>

# Random tensors

In [14]:
# creating two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(25) # setting the seed for reproducibility
random_1 = random_1.normal(shape=(3,2)) # creating tensor from a normal distribution

random_2 = tf.random.Generator.from_seed(25)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.14371012, -0.34646833],
        [ 1.1456194 , -0.416     ],
        [ 0.43369916,  1.0241015 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.14371012, -0.34646833],
        [ 1.1456194 , -0.416     ],
        [ 0.43369916,  1.0241015 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [15]:
# shuffle a tensor
not_shuffled = tf.constant([[1,2],
                            [3,4],
                            [5,6]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [1, 2],
       [3, 4]], dtype=int32)>

### Global Seed

*   Controls all random numbers in the whole program
*   Makes the whole program’s random results the same every time I run it.




In [16]:
tf.random.set_seed(42)              # Sets global seed for consistency
print(tf.random.uniform([2, 2]))    # Same numbers every time

tf.Tensor(
[[0.6645621  0.44100678]
 [0.3528825  0.46448255]], shape=(2, 2), dtype=float32)


### Operation Seed

*   Controls only one specific random operation.
*   Makes only that one random result the same every time, even if the rest of the program is different.

In [17]:
print(tf.random.uniform([2, 2], seed=7))  # This specific result stays the same every time

tf.Tensor(
[[0.8627677  0.6567626 ]
 [0.99054587 0.9031013 ]], shape=(2, 2), dtype=float32)


#### Other ways to make tensors

In [18]:
# all ones
tf.ones(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [19]:
# all zeros
tf.zeros(shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

### Convert numpy arrays into tensors

##### A matrix or tensor is typically represented by a capital letter (e.g. `X` or `A`) where as a vector is typically represented by a lowercase letter (e.g. `y` or `b`).

In [20]:
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32)     # created a NumPy array between 1 and 25
A = tf.constant(numpy_A, shape=(2,4,3))       # the shape total (2*4*3) has to match the number of elements in the array

numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

# Getting information tensors (shape, rank, size)

* Shape: The size of each dimension in a tensor.
(e.g., shape (3, 2) means 3 rows, 2 columns)

* Rank: Number of dimensions.
(e.g., scalar: rank 0, vector: rank 1, matrix: rank 2)

* Axis: A specific dimension in the tensor.
(e.g., for a 3x2 matrix, axis 0 is rows, axis 1 is columns)

* Size: Total number of elements.
(e.g., a shape of (3, 2) has size 6)

In [21]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [22]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [23]:
# getting various attributes of tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions: ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along axis 0 of tensor: ", rank_4_tensor.shape[0])
print("Elements along last axis of tensor: ", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5): ", tf.size(rank_4_tensor).numpy()) #.numpy() converts to numpy array

Datatype of every element:  <dtype: 'float32'>
Number of dimensions:  4
Shape of tensor:  (2, 3, 4, 5)
Elements along axis 0 of tensor:  2
Elements along last axis of tensor:  5
Total number of elements (2*3*4*5):  120


In [24]:
# first 2 items of each dimensions
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [25]:
# selecting the first item from each of the first three dimensions and all items from the fourth
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [26]:
# creating a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[1,2],
                             [3,4]])

# getting the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [27]:
# adding an extra dimension
rank_3_tensor = rank_2_tensor[..., tf.newaxis]                # in Python, "..." means, 'all dimensions prior to'
rank_2_tensor, rank_3_tensor                                  # shape (2,2), shape (2,2,1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[1],
         [2]],
 
        [[3],
         [4]]], dtype=int32)>)

#### Same thing can be achievable by using `tf.expand_dims()`.

In [28]:
tf.expand_dims(rank_2_tensor, axis=-1) # axis=-1 means adding a new dimension at end

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

# Manipulating tensors (tensor operations)

In [29]:
# add values
tensor = tf.constant([[1,2],
                      [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

#### Original tensor will be unchanged. Same way for multiplication and subtraction.

###### `.multiply()` function is an alternative. Similarly, main value will be same.

In [30]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

### Matrix multiplication

##### `tf.matmul()` function used for that.

##### The inner dimensions must match:
*   (3, 5) @ (3, 5) won't work
*   (5, 3) @ (3, 5) will work
*   (3, 5) @ (5, 3) will work

##### The resulting matrix has the shape of the outer dimensions:
*   (5, 3) @ (3, 5) -> (5, 5)
*   (3, 5) @ (5, 3) -> (3, 3)


> '@' in Python is the symbol for matrix multiplication.






In [31]:
# matrix multiplication in tensorflow
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [32]:
# matrix multiplication with Python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

#### If I create two (3,2) tensor, it won't take matrix multiplication. Therefore, I have two option:



*   tf.reshape()
*   tf.transpose()



In [33]:
# Creating (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Creating another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [34]:
# Example of reshape (3, 2) -> (2, 3)
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [35]:
# multiplying by reshaping
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [36]:
# Example of transpose (3, 2) -> (2, 3)
tf.transpose(X) # no need to mention shape

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [37]:
# Trying matrix multiplication by 'transpose()' function
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [38]:
# I can achieve the same result with parameters
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

#### The Dot Product

In [39]:
# Performing the dot product on X and Y (requires X to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

#### `tf.transpose()` and `tf.reshape()` both will work, but may give different result. Now, I will show examples and reason.

In [40]:
# performing matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [41]:
# performing matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

#### Calling `tf.reshape()` and `tf.transpose()` on `Y` don't necessariy result in the same values.

In [42]:
# checking values of Y, reshaped Y and transposed Y
print("Normal Y: ")
print(Y, "\n")

print("Y reshaped to (2,3): ")
print(tf.reshape(Y,(2,3)), "\n")

print("Y transposed: ")
print(tf.transpose(Y))

Normal Y: 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3): 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


#### `tf.reshape():` Changes the shape of a tensor, keeping the data order the same.
#### `tf.transpose():` Swaps the axes of a tensor, changing the data layout.

# Changing the datatype of a tensor

In [43]:
# creating a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])

# creating a new tensor with default datatype (int32)
C = tf.constant([1, 7])
B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [44]:
# changing from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [45]:
# changing from int32 to float32
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

# Getting the absolute value

##### absolute values means `all values are positive`. `tf.abs()` fn uses for that.

In [46]:
# creating tensor with negative values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [47]:
# getting the absolute value
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

# Finding the min, max, mean, sum (aggregation)

#### aggregate means performing a calculation on a whole tensor.



*   tf.reduce_min() - finding the minimum value in a tensor.
*   tf.reduce_max() - finding the maximum value in a tensor.
*   tf.reduce_mean() - finding the mean of all elements in a tensor.
*   tf.reduce_sum() - finding the sum of all elements in a tensor.



In [48]:
# creating a tensor with 50 random values between 0 and 100
import numpy as np
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([70, 51, 96, 91, 63, 28, 72, 86,  9,  5, 90, 71,  8, 61, 16, 56, 53,
       32, 46, 23, 63, 25, 98,  4,  9, 30, 20, 68, 32, 27, 42, 92, 81,  6,
       80, 29,  1,  2, 11,  0, 91, 30, 43, 95, 21, 94,  1, 55,  0, 93])>

In [49]:
# finding the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [50]:
# finding the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [51]:
# finding the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=45>

In [52]:
# finding the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2270>

# Finding the positional maximum and minimum


*   tf.argmax() - finding the position of the maximum element in a given tensor.
*   tf.argmin() - finding the position of the minimum element in a given tensor.



In [53]:
# creating a tensor with 50 values between 0 and 1
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.89334109, 0.23616937, 0.12541352, 0.94357058, 0.63260733,
       0.73376293, 0.7809823 , 0.79124157, 0.00396612, 0.118976  ,
       0.77723987, 0.86658218, 0.13453087, 0.10062696, 0.98914152,
       0.32256082, 0.88852031, 0.33420576, 0.17120165, 0.72153563,
       0.65560413, 0.00765365, 0.09331246, 0.35112077, 0.86234352,
       0.44662531, 0.93135564, 0.84939572, 0.55056256, 0.8911742 ,
       0.21603952, 0.04440583, 0.86880778, 0.23025869, 0.11005524,
       0.24919871, 0.18417614, 0.88791507, 0.6627992 , 0.70309295,
       0.69465804, 0.5695034 , 0.64099706, 0.51217798, 0.64505851,
       0.39589754, 0.756662  , 0.36647244, 0.86417109, 0.18934896])>

In [54]:
# maximum element position of F
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=14>

In [55]:
# minimum element position of F
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=8>

# Squeezing a tensor (removing all single dimensions)
#### If I need to remove single-dimensions from a tensor (dimensions with size 1), I can use `tf.squeeze()`

In [56]:
# Creating a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [57]:
# Squeezing tensor G (removing all 1 dimensions)
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

# One-hot encoding

In [58]:
# creating a list of indices
some_list = [0,1,2,3]

# one hot encode them
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

#### I can also specify values for `on_value` and `off_value` instead of the default `0` and `1`.

In [59]:
# specifying custom values
tf.one_hot(some_list, depth=4, on_value="Yes", off_value="No")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yes', b'No', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No'],
       [b'No', b'No', b'Yes', b'No'],
       [b'No', b'No', b'No', b'Yes']], dtype=object)>

# Squaring, log, square root

In [60]:
# creating a new tensor
H = tf.constant(np.arange(1,10))
H

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [61]:
# square
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [62]:
# directly finding the sqrt will give error as it's integer.
# converting it to float32
H = tf.cast(H, dtype=tf.float32)
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [63]:
# finding the log also requires float
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Manipulating 'tf.Variable' tensors
#### Tensors created with tf.Variable() can be changed in place using methods such as:

*   `.assign()` - assign a different value to a particular index of a variable tensor.
*   `.add_assign()` - add to an existing value and reassign it at a particular index of a variable tensor.

In [64]:
# creating a variable tensor
I = tf.Variable(np.arange(0,5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [65]:
# changing a value
I.assign([0,1,2,3,50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [66]:
# add function will make summation
I.assign_add([10,10,10,10,10])
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>